version: "3.3"
services:
  db:
    image: postgres:12.6
    environment:
      POSTGRES_USER: mentorados
      POSTGRES_PASSWORD: mentorados
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgres://mentorados:mentorados@db/mentorados"
      EMAIL_SENDER_ADDRESS: "mentor@alumniei.pt"
      BASE_URL: "http://localhost:3000"
