version: "3.9"
services:
  db:
    image: postgres:12.6
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    entrypoint: ["/app/entrypoint.sh"]
    command: ["rails", "server", "-b", "0.0.0.0","-p","3000"]
    environment: 
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"